name: Release

on:
  repository_dispatch

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install fetch
        run: brew install fetch
      
      - name: Create tmp folder
        run: mkdir $TMPDIR/tauri_release

      - name: Fetch latest release
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_URL: ${{ secrets.REPO_URL }}
        run: fetch --repo="$REPO_URL" --release-asset="([Vv]ideo[.-][cC]alling[.-]*)|(latest.json)" --tag=">=0" $TMPDIR/tauri_release

      - name: Create Release
        run: |
          # Get version from latest.json
          VERSION=$(jq -r '.version' "$TMPDIR/tauri_release/Latest.json")

          gh release create "$VERSION" $TMPDIR/tauri_release/* \
            --title "Release $VERSION" \
            --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}