name: Release

on:
  repository_dispatch

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Install fetch
        run: brew install fetch

      - name: Fetch latest release
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_URL: ${{ secrets.REPO_URL }}
        run: fetch --repo="$REPO_URL" --release-asset=".*" --tag=">=0" $TMPDIR

      - name: Create Release
        run: |
          # Get version from latest.json
          VERSION=$(jq -r '.version' "$TMPDIR/Latest.json")

          gh release create "$VERSION" $TMPDIR/* \
            --title "Release $VERSION" \
            --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}